[package]
name = "leipzig-typst"
version = "0.0.1"
entrypoint = "leipzig-typst.typ"
authors = ["Lukas Böhm"]
license = "MIT"
description = "Leipzig slide template in typst"
repository = "https://github.com/lukasbm/leipzig-typst"
exclude = ["README.md"]
